/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import util.uiManagement;
import java.lang.ArrayIndexOutOfBoundsException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arty
 */
public class employeeForm extends javax.swing.JFrame {

    /**
     * Creates new form employeeForm
     */
    
    Connection c = util.dbConnection.getDatabase();
    uiManagement ui = new uiManagement();
    private DefaultTableModel model = new DefaultTableModel();
    
    public employeeForm() {
        initComponents();
        ui.setUI();
        model = (DefaultTableModel) emTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeLabel = new javax.swing.JLabel();
        mainFormButton = new javax.swing.JButton();
        emIDLabel = new javax.swing.JLabel();
        emFirstNameLabel = new javax.swing.JLabel();
        emLastNameLabel = new javax.swing.JLabel();
        emDOBLabel = new javax.swing.JLabel();
        emPositionLabel = new javax.swing.JLabel();
        emAddressLabel = new javax.swing.JLabel();
        emTelLabel = new javax.swing.JLabel();
        emLastNameField = new javax.swing.JTextField();
        emDOBField = new javax.swing.JTextField();
        emFirstNameField = new javax.swing.JTextField();
        emIDField = new javax.swing.JTextField();
        emAddressField = new javax.swing.JTextField();
        emTelField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        seperator = new javax.swing.JSeparator();
        tableScrollPane = new javax.swing.JScrollPane();
        emTable = new javax.swing.JTable();
        emPositionComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ພັບຈີຄລີນິກ - ພະແນກພະນັກງານ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        employeeLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 36)); // NOI18N
        employeeLabel.setText("ພະແນກພະນັກງານ");

        mainFormButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        mainFormButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        mainFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFormButtonActionPerformed(evt);
            }
        });

        emIDLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emIDLabel.setText("ລະຫັດພະນັກງານ");

        emFirstNameLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emFirstNameLabel.setText("ຊື່ພະນັກງານ");

        emLastNameLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emLastNameLabel.setText("ນາມສະກຸນພະນັກງານ");

        emDOBLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emDOBLabel.setText("ວັນເດືອນປີເກີດພະນັກງານ");

        emPositionLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emPositionLabel.setText("ຕຳແໜ່ງພະນັກງານ");

        emAddressLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emAddressLabel.setText("ທີ່ຢູ່ພະນັກງານ");

        emTelLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emTelLabel.setText("ໝາຍເລກຕິດຕໍ່");

        emLastNameField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        emDOBField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emDOBField.setText("YYYY-MM-DD");

        emFirstNameField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        emIDField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emIDField.setText("EM***");

        emAddressField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        emTelField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        addButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        addButton.setText("ເພີ່ມ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        selectButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        selectButton.setText("ເລືອກ");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        editButton.setText("ແກ້ໄຂ");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        deleteButton.setText("ລົບ");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        refreshButton.setText("ໂຫຼດໃໝ່");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        clearButton.setText("ລ້າງ");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        emTable.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ລະຫັດພະນັກງານ", "ຊື່", "ນາມສະກຸນ", "ວັນເດືອນປີເກີດ", "ຕຳແໜ່ງ", "ທີ່ຢູ່", "ໝາຍເລກຕິດຕໍ່"
            }
        ));
        emTable.getTableHeader().setFont(new java.awt.Font("Phetsarath OT", 0, 14));
        tableScrollPane.setViewportView(emTable);

        emPositionComboBox.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        emPositionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ທ່ານໝໍ", "ພະຍາບານ", "ໝໍອະນາໄມ", "ນັກສຶກສາແພດ", "ບັນຊີ", "ບໍລິການ", "ບໍລິຫານ", "ພະນັກງານເຮັດຄວາມສະອາດ", "ຍາມ" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableScrollPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seperator)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainFormButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(employeeLabel)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emIDLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emDOBLabel)
                            .addComponent(emLastNameLabel)
                            .addComponent(emFirstNameLabel)
                            .addComponent(emAddressLabel)
                            .addComponent(emTelLabel)
                            .addComponent(emPositionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emIDField)
                            .addComponent(emFirstNameField)
                            .addComponent(emLastNameField)
                            .addComponent(emDOBField)
                            .addComponent(emAddressField)
                            .addComponent(emTelField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(emPositionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(mainFormButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emIDLabel)
                    .addComponent(emIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emFirstNameLabel)
                    .addComponent(emFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emLastNameLabel)
                    .addComponent(emLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emDOBLabel)
                    .addComponent(emDOBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emPositionLabel)
                    .addComponent(emPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emAddressLabel)
                    .addComponent(emAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emTelLabel)
                    .addComponent(emTelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(selectButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainFormButtonActionPerformed
        // TODO add your handling code here:
        mainForm form = new mainForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainFormButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            int rowCount = emTable.getRowCount()-1;
            while (rowCount > -1){
                model.removeRow(rowCount--);
            }
            String sql = "call initEmployee()";
            ResultSet rs = c.createStatement().executeQuery(sql);
            while (rs.next()){
                Vector row = new Vector();
                row.add(rs.getString("em_id"));
                row.add(rs.getString("em_firstName"));
                row.add(rs.getString("em_lastName"));
                row.add(rs.getDate("em_dateOfBirth"));
                row.add(rs.getString("em_position"));
                row.add(rs.getString("em_address"));
                row.add(rs.getString("em_telephone"));
                model.addRow(row);
            }
            rs.close();
            emTable.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String idF = emIDField.getText();
        String fNameF = emFirstNameField.getText();
        String lNameF = emLastNameField.getText();
        String dobF = emDOBField.getText();
        String positionF = (String)emPositionComboBox.getSelectedItem();
        String addressF = emAddressField.getText();
        String telF = emTelField.getText();
        int statementNumber = 0;
        if (idF.equals("")){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ລະຫັດພະນັກງານ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (fNameF.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ຊື່", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (lNameF.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ນາມສະກຸນ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (dobF.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ວັນເດືອນປີເກີດ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (addressF.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ທີ່ຢູ່", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (telF.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ໝາຍເລກຕິດຕໍ່", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String sql = "call newEmployee('"+idF+"','"+fNameF+"','"+lNameF+"', '"+dobF+"', '"+positionF+"', '"+addressF+"', '"+telF+"')";
                Statement s = c.createStatement();
                statementNumber = s.executeUpdate(sql);
                if (statementNumber != 0){
                    JOptionPane.showMessageDialog(rootPane, "ເພີ່ມຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                    formWindowOpened(null);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ເພີ່ມຂໍ້ມູນບໍ່ສຳເລັດ", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
        try {
            int index = emTable.getSelectedRow();
            String idF = emTable.getValueAt(index, 0).toString();
            String fNameF = emTable.getValueAt(index, 1).toString();
            String lNameF = emTable.getValueAt(index, 2).toString();
            String dobF = emTable.getValueAt(index, 3).toString();
            String positionF = emTable.getValueAt(index, 4).toString();
            String addressF = emTable.getValueAt(index, 5).toString();
            String telF = emTable.getValueAt(index, 6).toString();
            emTable.getValueAt(index, 6).toString();
            emIDField.setText(idF);
            emFirstNameField.setText(fNameF);
            emLastNameField.setText(lNameF);
            emDOBField.setText(dobF);
            emPositionComboBox.setSelectedItem(positionF);
            emAddressField.setText(addressF);
            emTelField.setText(telF);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາເລືອກຂໍ້ມູນໃນຕາຕະລາງ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String sql = "update tbEmployee set em_firstName = ?, em_lastName = ?, em_dateOfBirth = ?, em_position = ?, em_address = ?, em_telephone = ? where em_id = ?";
        try {
            int statementNumber = 0;
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, emFirstNameField.getText());
            ps.setString(2, emLastNameField.getText());
            ps.setString(3, emDOBField.getText());
            ps.setString(4, String.valueOf(emPositionComboBox.getSelectedItem()));
            ps.setString(5, emAddressField.getText());
            ps.setString(6, emTelField.getText());
            ps.setString(7, emIDField.getText());
            statementNumber = ps.executeUpdate();
            if (statementNumber != 0){
                JOptionPane.showMessageDialog(rootPane, "ແກ້ໄຂຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                formWindowOpened(null);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ແກ້ໄຂຂໍ້ມູນບໍ່ສຳເລັດ\nໝາຍເຫດ: ຖ້າຕ້ອງການແກ້ໄຂລະຫັດພະນັກງານໃຫ້ໄປແກ້ທີ່ຖານຂໍ້ມູນໂດຍກົງ", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String idF = emIDField.getText();
        String fNameF = emFirstNameField.getText();
        String lNameF = emLastNameField.getText();
        String dobF = emDOBField.getText();
        String positionF = (String)emPositionComboBox.getSelectedItem();
        String addressF = emAddressField.getText();
        String telF = emTelField.getText();
        if ((idF.equals("")) || (fNameF.equals("")) || (lNameF.equals("")) || (dobF.equals("")) || (addressF.equals("")) || (telF.equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ມູນບາງຢ່າງບໍ່ຖືກຕ້ອງ, ບໍ່ສາມາດດຳເນີນການຕໍ່ໄດ້", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String sql1, sql2;
                sql1 = "call selectEmployee('"+idF+"', '"+fNameF+"', '"+lNameF+"', '"+dobF+"', '"+positionF+"', '"+addressF+"', '"+telF+"')";
                ResultSet rs = c.createStatement().executeQuery(sql1);
                if (rs.next()){
                    sql2 = "call removeEmployee('"+idF+"', '"+fNameF+"', '"+lNameF+"', '"+dobF+"', '"+positionF+"', '"+addressF+"', '"+telF+"')";
                    int statementNumber = 0;
                    Statement s = c.createStatement();
                    statementNumber = s.executeUpdate(sql2);
                    if (statementNumber != 0){
                        JOptionPane.showMessageDialog(rootPane, "ລົບຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                        formWindowOpened(null);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ລົບໄຂຂໍ້ມູນບໍ່ສຳເລັດ", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ບໍ່ພົບຂໍ້ມູນທີ່ຕ້ອງການລົບ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        this.formWindowOpened(null);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        emIDField.setText("");
        emFirstNameField.setText("");
        emLastNameField.setText("");
        emDOBField.setText("");
        emAddressField.setText("");
        emTelField.setText("");
        emPositionComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emAddressField;
    private javax.swing.JLabel emAddressLabel;
    private javax.swing.JTextField emDOBField;
    private javax.swing.JLabel emDOBLabel;
    private javax.swing.JTextField emFirstNameField;
    private javax.swing.JLabel emFirstNameLabel;
    private javax.swing.JTextField emIDField;
    private javax.swing.JLabel emIDLabel;
    private javax.swing.JTextField emLastNameField;
    private javax.swing.JLabel emLastNameLabel;
    private javax.swing.JComboBox<String> emPositionComboBox;
    private javax.swing.JLabel emPositionLabel;
    private javax.swing.JTable emTable;
    private javax.swing.JTextField emTelField;
    private javax.swing.JLabel emTelLabel;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JButton mainFormButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JSeparator seperator;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
