/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;
import java.sql.Connection;
import util.dbConnection;
import util.uiManagement;

/**
 *
 * @author arty
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    uiManagement ui = new uiManagement();
    Connection c = dbConnection.getDatabase();
    public mainForm() {
        initComponents();
        ui.setUI();
        if(c == null){
            JOptionPane.showMessageDialog(rootPane, "ທ່ານບໍ່ໄດ້ເຊື່ອມຕໍ່ໂປຣແກຣມກັບຖານຂໍ້ມູນ ໂປຣແກຣມຈະອອກໂດຍອັດຕະໂນມັດ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        saleFormButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        doctorFormButton = new javax.swing.JButton();
        invoiceFormButton = new javax.swing.JButton();
        medicStorageFormButton1 = new javax.swing.JButton();
        employee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ພັບຈີຄລີນິກ - ໜ້າຫຼັກ");
        setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        mainLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 36)); // NOI18N
        mainLabel.setText("ພັບຈີຄລີນິກ");
        mainLabel.setToolTipText("");
        mainLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainLabelMouseClicked(evt);
            }
        });

        saleFormButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        saleFormButton.setText("ພະແນກຂາຍຢາ");
        saleFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleFormButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        exitButton.setText("ອອກ");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        doctorFormButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        doctorFormButton.setText("ຫ້ອງກວດພະຍາດ");
        doctorFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFormButtonActionPerformed(evt);
            }
        });

        invoiceFormButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        invoiceFormButton.setText("ຜົນກວດສຸຂະພາບ");
        invoiceFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceFormButtonActionPerformed(evt);
            }
        });

        medicStorageFormButton1.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicStorageFormButton1.setText("ຄັງຢາ");
        medicStorageFormButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicStorageFormButton1ActionPerformed(evt);
            }
        });

        employee.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        employee.setText("ພະນັກງານ");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(mainLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(medicStorageFormButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(invoiceFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saleFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(doctorFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mainLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicStorageFormButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int confirmStatus = JOptionPane.showConfirmDialog(rootPane, "ທ່ານຕ້ອງການອອກຈາກໂປຣແກຣມຫຼືບໍ່", "ອອກຈາກໂປຣແກຣມ", JOptionPane.YES_NO_OPTION);
        if (confirmStatus == 0){
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void medicStorageFormButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicStorageFormButton1ActionPerformed
        // TODO add your handling code here:
        medicStorageForm form = new medicStorageForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_medicStorageFormButton1ActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
        employeeForm form = new employeeForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employeeActionPerformed

    private void saleFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleFormButtonActionPerformed
        // TODO add your handling code here:
        saleForm form = new saleForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saleFormButtonActionPerformed

    private void doctorFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFormButtonActionPerformed
        // TODO add your handling code here:
        doctorForm form = new doctorForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doctorFormButtonActionPerformed

    private void invoiceFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceFormButtonActionPerformed
        // TODO add your handling code here:
        invoiceForm form = new invoiceForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_invoiceFormButtonActionPerformed

    private void mainLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "ພັບຈີຄລີນິກ ເວີຊັນທົດລອງ, ພັດທະນາໂດຍທ້າວພິລະພົນ ອິນທະວົງສາ ປີ 2019\n"
                + "ຂໍ້ມູນເພີ່ມເຕີມທີ່ https://github.com/ArtyDev57/...", "ກ່ຽວກັບໂປຣແກຣມ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mainLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctorFormButton;
    private javax.swing.JButton employee;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton invoiceFormButton;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton medicStorageFormButton1;
    private javax.swing.JButton saleFormButton;
    // End of variables declaration//GEN-END:variables
}
