/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.uiManagement;

/**
 *
 * @author arty
 */
public class medicStorageForm extends javax.swing.JFrame {

    /**
     * Creates new form medicStorageForm
     */
    uiManagement ui = new util.uiManagement();
    Connection c = util.dbConnection.getDatabase();
    private DefaultTableModel model = new DefaultTableModel();
    
    public medicStorageForm() {
        initComponents();
        ui.setUI();
        model = (DefaultTableModel) medicTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicStorageLabel = new javax.swing.JLabel();
        mainFormButton = new javax.swing.JButton();
        medicIDLabel = new javax.swing.JLabel();
        medicNameLabel = new javax.swing.JLabel();
        medicPriceLabel = new javax.swing.JLabel();
        medicTypeLabel = new javax.swing.JLabel();
        medicIDField = new javax.swing.JTextField();
        medicNameField = new javax.swing.JTextField();
        medicPriceField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        stockButton = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        tableScrollPane = new javax.swing.JScrollPane();
        medicTable = new javax.swing.JTable();
        medicTypeComboBox = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ພັບຈີຄລີນິກ - ຄັງຢາ");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        medicStorageLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 36)); // NOI18N
        medicStorageLabel.setText("ຄັງຢາ");

        mainFormButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        mainFormButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        mainFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFormButtonActionPerformed(evt);
            }
        });

        medicIDLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicIDLabel.setText("ລະຫັດຢາ");

        medicNameLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicNameLabel.setText("ຊື່ຢາ");

        medicPriceLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicPriceLabel.setText("ລາຄາ");

        medicTypeLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicTypeLabel.setText("ປະເພດຢາ");

        medicIDField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicIDField.setText("MED***");

        medicNameField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        medicPriceField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicPriceField.setText("0");

        addButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        addButton.setText("ເພີ່ມ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        selectButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        selectButton.setText("ເລືອກ");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        editButton.setText("ແກ້ໄຂ");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        deleteButton.setText("ລົບ");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        stockButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        stockButton.setText("ເພີ່ມເຂົ້າຄັງ");
        stockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButtonActionPerformed(evt);
            }
        });

        medicTable.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ລະຫັດຢາ", "ຊື່ຢາ", "ລາຄາ", "ປະເພດຢາ", "ປະລິມານ"
            }
        ));
        medicTable.getTableHeader().setFont(new java.awt.Font("Phetsarath OT", 0, 14));
        tableScrollPane.setViewportView(medicTable);

        medicTypeComboBox.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ຢາສາມັນປະຈຳບ້ານ", "ຢາແພດສັ່ງ", "ຢາອັນຕະລາຍ", "ອຸປະກອນການແພດ" }));
        medicTypeComboBox.setToolTipText("");

        refreshButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        refreshButton.setText("ໂຫຼດໃໝ່");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        clearButton.setText("ລ້າງ");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Separator)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainFormButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(medicStorageLabel)
                        .addGap(258, 258, 258))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(medicIDLabel)
                                .addGap(18, 18, 18)
                                .addComponent(medicIDField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(medicNameLabel)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(medicPriceLabel)
                                            .addComponent(medicTypeLabel))
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medicNameField)
                                    .addComponent(medicPriceField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stockButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(refreshButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearButton)
                                        .addGap(0, 26, Short.MAX_VALUE))
                                    .addComponent(medicTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tableScrollPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(medicStorageLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mainFormButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicIDLabel)
                    .addComponent(medicIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicNameLabel)
                    .addComponent(medicNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicPriceLabel)
                    .addComponent(medicPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicTypeLabel)
                    .addComponent(medicTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addButton)
                        .addComponent(selectButton)
                        .addComponent(editButton)
                        .addComponent(deleteButton)
                        .addComponent(refreshButton)
                        .addComponent(clearButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainFormButtonActionPerformed
        // TODO add your handling code here:
        mainForm form = new mainForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainFormButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            int rowCount = medicTable.getRowCount()-1;
            while (rowCount > -1){
                model.removeRow(rowCount--);
            }
            String sql = "call initMedicStorage()";
            ResultSet rs = c.createStatement().executeQuery(sql);
            while (rs.next()){
                Vector row = new Vector();
                row.add(rs.getString("med_id"));
                row.add(rs.getString("med_name"));
                row.add(rs.getInt("med_price"));
                row.add(rs.getString("med_type"));
                row.add(rs.getInt("med_quantity"));
                model.addRow(row);
            }
            rs.close();
            medicTable.setModel(model);
            
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String idF = medicIDField.getText();
        String nameF = medicNameField.getText();
        String priceF = medicPriceField.getText();
        String typeF = (String)medicTypeComboBox.getSelectedItem();
        try {
            Integer.parseInt(priceF);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "ລາຄາຕ້ອງແມ່ນຕົວເລກເທົ່ານັ້ນ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
        int statementNumber = 0;
        int price = Integer.valueOf(priceF);
        if (idF.equals("")){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ລະຫັດຢາ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (nameF.equals("")){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ຊື່ຢາ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (String.valueOf(price).equals("")){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ລາຄາຢາ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else if (price <= 0) {
            JOptionPane.showMessageDialog(rootPane, "ຕ້ອງມີລາຄາຕັ້ງແຕ່1ກີບຂຶ້ນໄປ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String sql = "call newMedic('"+idF+"', '"+nameF+"', "+price+", '"+typeF+"', 0)";
                Statement s = c.createStatement();
                statementNumber = s.executeUpdate(sql);
                if (statementNumber != 0){
                    JOptionPane.showMessageDialog(rootPane, "ເພີ່ມຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                    formWindowOpened(null);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ເພີ່ມຂໍ້ມູນບໍ່ສຳເລັດ", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
        try {
            int index = medicTable.getSelectedRow();
            String id = medicTable.getValueAt(index, 0).toString();
            String name = medicTable.getValueAt(index, 1).toString();
            String price = medicTable.getValueAt(index, 2).toString();
            String type = medicTable.getValueAt(index, 3).toString();
            medicIDField.setText(id);
            medicNameField.setText(name);
            medicPriceField.setText(price);
            medicTypeComboBox.setSelectedItem(type);
        } catch (ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາເລືອກຂໍ້ມູນໃນຕາຕະລາງ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String sql = "update tbMedicStorage set med_name = ?, med_price = ?, med_type = ? where med_id = ?";
        try {
            int statementNumber = 0;
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, medicNameField.getText());
            ps.setInt(2, Integer.valueOf(medicPriceField.getText()));
            ps.setString(3, String.valueOf(medicTypeComboBox.getSelectedItem()));
            ps.setString(4, medicIDField.getText());
            statementNumber = ps.executeUpdate();
            if (statementNumber != 0){
                JOptionPane.showMessageDialog(rootPane, "ແກ້ໄຂຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                formWindowOpened(null);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ແກ້ໄຂຂໍ້ມູນບໍ່ສຳເລັດ\nໝາຍເຫດ: ຖ້າຕ້ອງການແກ້ໄຂລະຫັດຢາໃຫ້ໄປແກ້ທີ່ຖານຂໍ້ມູນໂດຍກົງ", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String idF = medicIDField.getText();
        String nameF = medicNameField.getText();
        String priceF = medicPriceField.getText();
        String typeF = (String)medicTypeComboBox.getSelectedItem();
        if ((idF.equals("")) || (nameF.equals("")) || (priceF.equals("")) || (typeF.equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ມູນບາງຢ່າງບໍ່ຖືກຕ້ອງ, ບໍ່ສາມາດດຳເນີນການຕໍ່ໄດ້", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String sql1, sql2;
                sql1 = "call selectMedic('"+idF+"', '"+nameF+"', "+Integer.valueOf(priceF)+", '"+typeF+"')";
                ResultSet rs = c.createStatement().executeQuery(sql1);
                if (rs.next()){
                    sql2 = "call removeMedic('"+idF+"', '"+nameF+"', "+Integer.valueOf(priceF)+", '"+typeF+"')";
                    int statementNumber = 0;
                    Statement s = c.createStatement();
                    statementNumber = s.executeUpdate(sql2);
                    if (statementNumber != 0){
                        JOptionPane.showMessageDialog(rootPane, "ລົບຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                        formWindowOpened(null);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ລົບໄຂຂໍ້ມູນບໍ່ສຳເລັດ", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ບໍ່ພົບຂໍ້ມູນທີ່ຕ້ອງການລົບ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void stockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockButtonActionPerformed
        // TODO add your handling code here:
        stockMedicForm form = new stockMedicForm();
        form.setVisible(true);
    }//GEN-LAST:event_stockButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        this.formWindowOpened(null);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        medicIDField.setText("");
        medicNameField.setText("");
        medicPriceField.setText("");
        medicTypeComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_clearButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicStorageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicStorageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicStorageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicStorageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicStorageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton mainFormButton;
    private javax.swing.JTextField medicIDField;
    private javax.swing.JLabel medicIDLabel;
    private javax.swing.JTextField medicNameField;
    private javax.swing.JLabel medicNameLabel;
    private javax.swing.JTextField medicPriceField;
    private javax.swing.JLabel medicPriceLabel;
    private javax.swing.JLabel medicStorageLabel;
    private javax.swing.JTable medicTable;
    private javax.swing.JComboBox<String> medicTypeComboBox;
    private javax.swing.JLabel medicTypeLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton stockButton;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
