/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.view.JasperViewer;
import util.uiManagement;



/**
 *
 * @author arty
 */
public class saleForm extends javax.swing.JFrame {

    /**
     * Creates new form saleForm
     */
    Connection c = util.dbConnection.getDatabase();
    uiManagement ui = new uiManagement();
    private DefaultTableModel model = new DefaultTableModel();
    private DefaultComboBoxModel med = new DefaultComboBoxModel();
    public saleForm() {
        initComponents();
        ui.setUI();
        model = (DefaultTableModel) saleTable.getModel();
        med = (DefaultComboBoxModel) medicComboBox.getModel();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saleLabel = new javax.swing.JLabel();
        mainFormButton = new javax.swing.JButton();
        saleIDLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        medicLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        saleIDField = new javax.swing.JTextField();
        customerField = new javax.swing.JTextField();
        medicComboBox = new javax.swing.JComboBox<>();
        quantityComboBox = new javax.swing.JComboBox<>();
        totalField = new javax.swing.JFormattedTextField();
        dateField = new javax.swing.JTextField();
        saleButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        seperator = new javax.swing.JSeparator();
        tableScrollPane = new javax.swing.JScrollPane();
        saleTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ພັບຈີຄລີນິກ - ພະແນກຂາຍຢາ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        saleLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 36)); // NOI18N
        saleLabel.setText("ພະແນກຂາຍຢາ");

        mainFormButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        mainFormButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        mainFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFormButtonActionPerformed(evt);
            }
        });

        saleIDLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        saleIDLabel.setText("ລະຫັດໃບບິນ");

        customerLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        customerLabel.setText("ລູກຄ້າ");

        medicLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicLabel.setText("ຢາ");

        quantityLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        quantityLabel.setText("ປະລິມານ");

        totalLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        totalLabel.setText("ຍອດລວມ");

        dateLabel.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        dateLabel.setText("ວັນເວລາ");

        saleIDField.setEditable(false);
        saleIDField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        customerField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        medicComboBox.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        medicComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                medicComboBoxItemStateChanged(evt);
            }
        });

        quantityComboBox.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        quantityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        quantityComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                quantityComboBoxItemStateChanged(evt);
            }
        });

        totalField.setEditable(false);
        totalField.setText("0");

        dateField.setEditable(false);
        dateField.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N

        saleButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        saleButton.setText("ຂາຍ");
        saleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonActionPerformed(evt);
            }
        });

        selectButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        selectButton.setText("ເລືອກ");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        editButton.setText("ແກ້ໄຂ");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        deleteButton.setText("ລົບ");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        refreshButton.setText("ໂຫຼດໃໝ່");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        clearButton.setText("ລ້າງ");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        reportButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        reportButton.setText("ລາຍງານ");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        billButton.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        billButton.setText("ອອກໃບບິນ");
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billButtonActionPerformed(evt);
            }
        });

        saleTable.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        saleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ລະຫັດໃບບິນ", "ລູກຄ້າ", "ຢາ", "ປະລິມານ", "ຍອດລວມ", "ວັນເວລາ"
            }
        ));
        saleTable.getTableHeader().setFont(new java.awt.Font("Phetsarath OT", 0, 14));
        tableScrollPane.setViewportView(saleTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saleIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(saleIDField)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerLabel)
                                .addGap(50, 50, 50)
                                .addComponent(customerField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainFormButton)
                                .addGap(178, 178, 178)
                                .addComponent(saleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medicLabel)
                                .addGap(67, 67, 67)
                                .addComponent(medicComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantityLabel)
                                .addGap(36, 36, 36)
                                .addComponent(quantityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGap(31, 31, 31)
                                .addComponent(totalField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seperator)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateLabel)
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(saleButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(selectButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(refreshButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clearButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(reportButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(billButton)
                                                .addGap(0, 10, Short.MAX_VALUE))
                                            .addComponent(dateField)))
                                    .addComponent(tableScrollPane))))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(mainFormButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleIDLabel)
                            .addComponent(saleIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLabel)
                            .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(saleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicLabel)
                    .addComponent(medicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleButton)
                    .addComponent(selectButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton)
                    .addComponent(clearButton)
                    .addComponent(reportButton)
                    .addComponent(billButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainFormButtonActionPerformed
        // TODO add your handling code here:
        mainForm form = new mainForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainFormButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            int rowCount = saleTable.getRowCount()-1;
            while (rowCount > -1) {                
                model.removeRow(rowCount--);
            }
            String sql = "call initSale()";
            ResultSet rs = c.createStatement().executeQuery(sql);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt("tbMedicSale.bill_id"));
                row.add(rs.getString("tbMedicSale.customer_name"));
                row.add(rs.getString("tbMedicStorage.med_name"));
                row.add(rs.getInt("tbMedicSale.quantity"));
                row.add(rs.getInt("tbMedicSale.total_price"));
                row.add(rs.getDate("tbMedicSale.bill_date"));
                model.addRow(row);
            }
            rs.close();
            saleTable.setModel(model);
            
            sql = "call getMedicName()";
            rs = c.createStatement().executeQuery(sql);
            while (rs.next()) {                
                med.addElement(rs.getString("med_name"));
            }
            rs.close();
            medicComboBox.setModel(med);
            
            calculate();
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void saleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleButtonActionPerformed
        // TODO add your handling code here:
        String customerF = customerField.getText();
        String medicF = (String)medicComboBox.getSelectedItem();
        String medID = "";
        String quantityS = (String)quantityComboBox.getSelectedItem();
        int quantity = Integer.parseInt(quantityS);
        int stockQuantity = 0;
        int statementNumber = 0;
        if (customerF.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາໃສ່ຊື່ລູກຄ້າ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
            String sqlR = "call getMedicIDByName('"+medicF+"')";
            ResultSet rs = c.createStatement().executeQuery(sqlR);
            if (rs.next()){
                medID = rs.getString("tbMedicStorage.med_id");
            }
            sqlR = "call getMedicStockQuantityByID('"+medID+"')";
            rs = c.createStatement().executeQuery(sqlR);
            if (rs.next()){
                stockQuantity = rs.getInt("tbMedicStorage.med_quantity");
            }
                if (stockQuantity >= quantity && stockQuantity != 0){
                String sql = "call addSale('"+customerF+"', '"+medID+"', "+quantity+")";
                Statement s = c.createStatement();
                statementNumber = s.executeUpdate(sql);
                if (statementNumber != 0){
                    JOptionPane.showMessageDialog(rootPane, "ຂາຍແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                    this.formWindowOpened(null);
                } else {
                JOptionPane.showMessageDialog(rootPane, "ດຳເນີນການບໍ່ສຳເລັດ, ກະລຸນາລອງໃໝ່", "ບໍ່ສຳເລັດຜົນ", HEIGHT);
                }
            } else {
                    JOptionPane.showMessageDialog(rootPane, "ຈຳນວນຢາໃນຄັງບໍ່ພຽງພໍຫຼືບໍ່ມີຢາຢູ່ໃນຄັງ", "ຂໍ້ຜິດພາດ", HEIGHT);
            }
            
            
        } catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_saleButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
        try {
            int index = saleTable.getSelectedRow();
            saleIDField.setText(String.valueOf(saleTable.getValueAt(index, 0)));
            customerField.setText(String.valueOf(saleTable.getValueAt(index, 1)));
            medicComboBox.setSelectedItem(saleTable.getValueAt(index, 2));
            quantityComboBox.setSelectedItem(saleTable.getValueAt(index, 3));
            totalField.setText(String.valueOf(saleTable.getValueAt(index, 4)));
            dateField.setText(String.valueOf(saleTable.getValueAt(index, 5)));
        } catch (ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(rootPane, "ກະລຸນາເລືອກຂໍ້ມູນໃນຕາຕະລາງ", "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "ບໍ່ອະນຸຍາດໃຫ້ແກ້ໄຂ", "ຕ້ອງຫ້າມ", JOptionPane.INFORMATION_MESSAGE);
        //to use this, create a database trigger that will change quantity in the stock automatically after update
        /*String medID = "";
        try {
            ResultSet rs = c.createStatement().executeQuery("call getMedicIDByName('"+String.valueOf(medicComboBox.getSelectedItem())+"')");
            if (rs.next()){
                medID = rs.getString("tbMedicStorage.med_id");              
            }
            int statementNumber = 0;
            String sql = "update tbMedicSale set customer = ?, med_id = ?, quantity = ? where bill_id = ?";
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, customerField.getText());
            ps.setString(2, medID);
            ps.setInt(3, Integer.parseInt(String.valueOf(quantityComboBox.getSelectedItem())));
            ps.setInt(4, Integer.parseInt(saleIDField.getText()));
            statementNumber = ps.executeUpdate();
            if (statementNumber != 0){
                JOptionPane.showMessageDialog(rootPane, "ແກ້ໄຂຂໍ້ມູນສຳເລັດແລ້ວ", "ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
                this.formWindowOpened(null);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ແກ້ໄຂຂໍ້ມູນບໍ່ສຳເລັດ\nໝາຍເຫດ: ບໍ່ສາມາດແກ້ໄຂລະຫັດໃບບິນໄດ້", "ບໍ່ສຳເລັດຜົນ", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        } */
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "ບໍ່ອະນຸຍາດໃຫ້ລົບ", "ຕ້ອງຫ້າມ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        this.formWindowOpened(null);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        saleIDField.setText("");
        customerField.setText("");
        totalField.setText("");
        dateField.setText("");
        medicComboBox.setSelectedIndex(-1);
        quantityComboBox.setSelectedIndex(-1);
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "ຈະມີໃຫ້ໃຊ້ໃນໄວໆນີ້", "ກຳລັງຈະມາ", JOptionPane.INFORMATION_MESSAGE);
        try {
            JasperPrint jp = JasperFillManager.fillReport("src/report/saleReport.jasper", null, c);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_reportButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "ຈະມີໃຫ້ໃຊ້ໃນໄວໆນີ້", "ກຳລັງຈະມາ", JOptionPane.INFORMATION_MESSAGE);
        try {
            JasperPrint jp = JasperFillManager.fillReport("src/report/billReport.jasper", null, c);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_billButtonActionPerformed

    private void medicComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_medicComboBoxItemStateChanged
        // TODO add your handling code here:
        calculate();
    }//GEN-LAST:event_medicComboBoxItemStateChanged

    private void quantityComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_quantityComboBoxItemStateChanged
        // TODO add your handling code here:
        calculate();
    }//GEN-LAST:event_quantityComboBoxItemStateChanged

    private void calculate(){
                
        try {
            String id = "";
        int total = 0;
        String quantity = (String) quantityComboBox.getSelectedItem();
        int quantityI = Integer.parseInt(quantity);
        int price = 0;
        String sql = "call getMedicIDByName('"+String.valueOf(medicComboBox.getSelectedItem())+"')";
        try {
            ResultSet rs = c.createStatement().executeQuery(sql);
            if (rs.next()){
                id = rs.getString("tbMedicStorage.med_id");
                sql = "call getMedicPriceByID('"+id+"')";
                rs = c.createStatement().executeQuery(sql);
                if (rs.next()){
                    price = rs.getInt("tbMedicStorage.med_price");
                    total = price * quantityI;
                    totalField.setText(String.valueOf(total));
                    
                } 
                
            } 
        } catch (SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "ຂໍ້ຜິດພາດໄດ້ເກີດຂຶ້ນ: "+ e, "ຂໍ້ຜິດພາດ", JOptionPane.WARNING_MESSAGE);
        }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "ການຄຳນວນລາຄາມີຂໍ້ຜິດພາດເນືອ່ງຈາກບໍ່ມີຄ່າທີ່ສາມາດຄຳນວນໄດ້\nບໍ່ຕ້ອງສົນໃຈຄຳເຕືອນນີ້", "ຂໍ້ບົກພ່ອງ", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField customerField;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton mainFormButton;
    private javax.swing.JComboBox<String> medicComboBox;
    private javax.swing.JLabel medicLabel;
    private javax.swing.JComboBox<String> quantityComboBox;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton saleButton;
    private javax.swing.JTextField saleIDField;
    private javax.swing.JLabel saleIDLabel;
    private javax.swing.JLabel saleLabel;
    private javax.swing.JTable saleTable;
    private javax.swing.JButton selectButton;
    private javax.swing.JSeparator seperator;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JFormattedTextField totalField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
